/** @format */

import Head from "next/head";
import Call from "../components/Call/Call";
import Navigation from "../components/Navigation/Navigation";
import styles from "../styles/global.module.scss";

export default function Home() {
   return (
      <div className={styles.container}>
         <Head>
            <title>Space Cadet</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <Navigation />
         <Call />
      </div>
   );
}
